CSS: TBela\CSS\Property\Config Class Reference
TBela\CSS\Property\Config Class Reference
Static Public Member Functions
static load ($file)
static exists ($path)
static getPath ($path, $default=null)
static getProperty ($name=null, $default=null)
static addSet ($shorthand, $pattern, $properties, $separator=null)
Static Protected Attributes
static $config
Member Function Documentation
addSet()
static TBela\CSS\Property\Config::addSet ($shorthand, $pattern, $properties, $separator = null) static
Add a configuration entry
Parameters
$shorthand
$pattern
$properties
bool $separator allow multiple values @ignore
Returns
array
exists()
static TBela\CSS\Property\Config::exists ($path) static
test the property existence
Parameters
string $path
Returns
bool
getPath()
static TBela\CSS\Property\Config::getPath ($path, $default = null) static
return property
Parameters
string $path
mixed | null $default
Returns
mixed|null @ignore
Referenced by TBela\CSS\Property\PropertyMap\__construct(), and TBela\CSS\Property\PropertyList\set().
getProperty()
static TBela\CSS\Property\Config::getProperty ($name = null, $default = null) static
get property if it exists, return $default if it does not exist
Parameters
string | null $name
mixed | null $default
Returns
array|mixed|null
Referenced by TBela\CSS\Property\PropertySet\__construct(), TBela\CSS\Property\PropertySet\reduce(), and TBela\CSS\Property\PropertyList\set().
load()
static TBela\CSS\Property\Config::load ($file) static
load properties configuration from a JSON file
Parameters
string $file
Member Data Documentation
$config
TBela\CSS\Property\Config::$config static protected
Initial value:
= [
        'properties' => [],
        'alias' => []
    ]
The documentation for this class was generated from the following file:
src/TBela/CSS/Property/Config.php