CSS: TBela\CSS\Property\PropertySet Class Reference
TBela\CSS\Property\PropertySet Class Reference
Public Member Functions
__construct (string $shorthand, array $config)
has ($property)
remove ($property)
set (string $name, $value, ?array $leadingcomments=null, ?array $trailingcomments=null, $vendor=null)
getProperties ()
render ($join="\n")
__toString ()
Protected Member Functions
expandProperties (array $result, ?array $leadingcomments=null, ?array $trailingcomments=null, $vendor=null)
expand ($value)
setProperty ($name, $value, $vendor=null)
Protected Attributes
array $config
array $properties = []
array $property_type = []
string $shorthand
Constructor & Destructor Documentation
__construct()
TBela\CSS\Property\PropertySet::__construct (string $shorthand, array $config)
PropertySet constructor.
Parameters
string $shorthand
array $config
Member Function Documentation
__toString()
TBela\CSS\Property\PropertySet::__toString ()
convert this object to string
Returns
string
Exceptions
expand()
TBela\CSS\Property\PropertySet::expand ($value) protected
expand shorthand property
Parameters
array | string $value
Returns
array|bool @ignore
Referenced by TBela\CSS\Property\PropertySet\set().
expandProperties()
TBela\CSS\Property\PropertySet::expandProperties (array $result, ?array $leadingcomments = null, ?array $trailingcomments = null, $vendor = null) protected
Parameters
array $result
array | null $leadingcomments
array | null $trailingcomments
string | null $vendor
Returns
$this
Referenced by TBela\CSS\Property\PropertySet\set().
getProperties()
TBela\CSS\Property\PropertySet::getProperties ()
return Property array
Returns
Property[]
Exceptions
Referenced by TBela\CSS\Property\PropertySet\render().
render()
TBela\CSS\Property\PropertySet::render ($join = "\n")
convert this object to string
Parameters
string $join
Returns
string
Exceptions
Referenced by TBela\CSS\Property\PropertySet\__toString().
set()
TBela\CSS\Property\PropertySet::set (string $name, $value, ?array $leadingcomments = null, ?array $trailingcomments = null, $vendor = null)
set property value
Parameters
string $name
array | string $value
array | null $leadingcomments
array | null $trailingcomments
null $vendor
Returns
PropertySet
setProperty()
TBela\CSS\Property\PropertySet::setProperty ($name, $value, $vendor = null) protected
set property
Parameters
string $name
string $value
null $vendor
Returns
PropertySet @ignore
Referenced by TBela\CSS\Property\PropertySet\expandProperties(), and TBela\CSS\Property\PropertySet\set().
The documentation for this class was generated from the following file:
src/Property/PropertySet.php