CSS: TBela\CSS\Value Class Reference
TBela\CSS\Value Class Reference
Public Member Functions
__get ($name)
__isset ($name)
render (array $options=[])
toObject ()
__toString ()
jsonSerialize ()
Static Public Member Functions
static renderTokens (array $tokens, array $options=[], $join=null)
static match (object $data, string $type)
static getClassName (string $type)
static matchToken ($token, $previousToken=null, $previousValue=null, $nextToken=null, $nextValue=null, int $index=null, array $tokens=[])
static getInstance ($data)
static equals (array $value, array $otherValue)
static format ($string, ?array &$comments=null)
static parse ($string, $property=null, bool $capture_whitespace=true, $context='', $contextName='', $preserve_quotes=false)
static reduce (array $tokens, array $options=[])
static getTokens (string $string, $capture_whitespace=true, $context='', $contextName='', $preserve_quotes=false)
static escape ($value)
static keywords ()
static matchKeyword (string $string, array $keywords=null)
static getNumericValue (?object $value, array $options=[])
static getRGBValue (object $value)
static getAngleValue (?object $value, array $options=[])
Protected Member Functions
__construct (object $data)
Static Protected Member Functions
static type ()
static matchDefaults ($token)
static validate ($data)
static doParse (string $string, bool $capture_whitespace=true, $context='', $contextName='', $preserve_quotes=false)
static indexOf (array $array, $search, int $offset=0)
static getType (string $token, $preserve_quotes=false)
Protected Attributes
stdClass $data = null
string $hash = null
Static Protected Attributes
static array $defaults = []
static array $keywords = []
static array $cache = []
Constructor & Destructor Documentation
__construct()
TBela\CSS\Value::__construct (object $data) protected
Value constructor.
Parameters
object $data
Member Function Documentation
__get()
TBela\CSS\Value::__get ($name)
get property
Parameters
string $name
Returns
mixed|null @ignore
__isset()
TBela\CSS\Value::__isset ($name)
Parameters
string $name
Returns
bool @ignore
__toString()
TBela\CSS\Value::__toString ()
convert to string
Returns
string
doParse()
static TBela\CSS\Value::doParse (string $string, bool $capture_whitespace = true, $context = '', $contextName = '', $preserve_quotes = false) static protected
parse a css value
Parameters
string $string
bool $capture_whitespace
string $context
string $contextName
bool $preserve_quotes
Returns
array
Reimplemented in TBela\CSS\Value\ShortHand, and TBela\CSS\Value\BackgroundColor.
equals()
static TBela\CSS\Value::equals (array $value, array $otherValue) static
compare parsed values
Parameters
array $value
array $otherValue
Returns
bool
Exceptions
Referenced by TBela\CSS\Property\PropertySet\getProperties().
escape()
static TBela\CSS\Value::escape ($value) static
escape multibyte sequence
Parameters
string $value
Returns
string
format()
static TBela\CSS\Value::format ($string, ?array & $comments = null) static
avoid parsing string
Parameters
$string
Returns
string | bool
getAngleValue()
static TBela\CSS\Value::getAngleValue (?object $value, array $options = []) static
Parameters
object | null $value
array $options
Returns
string|null
getClassName()
static TBela\CSS\Value::getClassName (string $type) static
get the class name of the specified type
Parameters
string $type
Returns
string
Referenced by TBela\CSS\Property\PropertySet\expand().
getInstance()
static TBela\CSS\Value::getInstance ($data) static
create an instance
Parameters
stdClass $data
Returns
Value
getNumericValue()
static TBela\CSS\Value::getNumericValue (?object $value, array $options = []) static
Parameters
Value | null $value
array $options
Returns
string
getRGBValue()
static TBela\CSS\Value::getRGBValue (object $value) static
Parameters
object $value
Returns
string
getTokens()
static TBela\CSS\Value::getTokens (string $string, $capture_whitespace = true, $context = '', $contextName = '', $preserve_quotes = false) static
parse a css value
Parameters
string $string
bool $capture_whitespace
string $context
string $contextName
booll $preserve_quotes
Returns
array|null
getType()
static TBela\CSS\Value::getType (string $token, $preserve_quotes = false) static protected
Parameters
string $token
bool $preserve_quotes
Returns
stdClass
indexOf()
static TBela\CSS\Value::indexOf (array $array, $search, int $offset = 0) static protected
Parameters
array $array
mixed $search
int $offset
Returns
false|int
keywords()
static TBela\CSS\Value::keywords () static
return the list of keywords
Returns
array @ignore
Reimplemented in TBela\CSS\Value\FontWeight, and TBela\CSS\Value\FontStretch.
match()
static TBela\CSS\Value::match (object $data, string $type) static
test if this object matches the specified type
Parameters
string $type
Returns
bool
Reimplemented in TBela\CSS\Value\Number.
matchDefaults()
static TBela\CSS\Value::matchDefaults ($token) static protected
Parameters
object $token
Returns
bool @ignore
matchKeyword()
static TBela\CSS\Value::matchKeyword (string $string, array $keywords = null) static
Parameters
string $string
array | null $keywords
Returns
string|null @ignore
Reimplemented in TBela\CSS\Value\BackgroundRepeat, and TBela\CSS\Value\BackgroundSize.
matchToken()
static TBela\CSS\Value::matchToken ($token, $previousToken = null, $previousValue = null, $nextToken = null, $nextValue = null, int $index = null, array $tokens = []) static
Parameters
object $token
object | null $previousToken
object | null $previousValue
object | null $nextToken
object | null $nextValue
int | null $index
array $tokens
Returns
bool
Reimplemented in TBela\CSS\Value\FontWeight, TBela\CSS\Value\BackgroundPosition, TBela\CSS\Value\BackgroundSize, TBela\CSS\Value\BackgroundImage, TBela\CSS\Value\FontStyle, TBela\CSS\Value\BackgroundColor, TBela\CSS\Value\FontVariant, TBela\CSS\Value\LineHeight, TBela\CSS\Value\OutlineWidth, TBela\CSS\Value\OutlineColor, and TBela\CSS\Value\FontFamily.
parse()
static TBela\CSS\Value::parse ($string, $property = null, bool $capture_whitespace = true, $context = '', $contextName = '', $preserve_quotes = false) static
parse a css value
Parameters
string $string
string | null $property
bool $capture_whitespace
string $context
string $contextName
bool $preserve_quotes
Returns
array
Referenced by TBela\CSS\Query\TokenSelectorValueAttributeFunctionColor\__construct(), TBela\CSS\Parser\append(), TBela\CSS\Property\PropertySet\expand(), TBela\CSS\Parser\Lexer\load(), TBela\CSS\Query\TokenSelectorValueAttributeFunctionColor\render(), TBela\CSS\Property\PropertySet\set(), TBela\CSS\Property\PropertyMap\set(), TBela\CSS\Property\Property\setValue(), and TBela\CSS\Element\setValue().
reduce()
static TBela\CSS\Value::reduce (array $tokens, array $options = []) static
remove unnecessary tokens
Parameters
array $tokens
array $options
Returns
array
Reimplemented in TBela\CSS\Value\BackgroundSize.
Referenced by TBela\CSS\Property\PropertyMap\set().
render()
TBela\CSS\Value::render (array $options = [])
convert this object to string
Parameters
array $options
Returns
string
Reimplemented in TBela\CSS\Value\BackgroundPosition, TBela\CSS\Value\Number, TBela\CSS\Value\LineHeight, TBela\CSS\Value\FontSize, TBela\CSS\Value\CssString, TBela\CSS\Value\Color, TBela\CSS\Value\FontWeight, TBela\CSS\Value\FontStretch, TBela\CSS\Value\InvalidCssString, TBela\CSS\Value\Operator, TBela\CSS\Value\Unit, TBela\CSS\Value\Whitespace, TBela\CSS\Value\BackgroundImage, TBela\CSS\Value\InvalidCssFunction, TBela\CSS\Value\Separator, TBela\CSS\Value\Comment, TBela\CSS\Value\CssFunction, TBela\CSS\Value\InvalidComment, TBela\CSS\Value\CssAttribute, TBela\CSS\Value\CssParenthesisExpression, TBela\CSS\Value\CssUrl, and TBela\CSS\Value\CssSrcFormat.
renderTokens()
static TBela\CSS\Value::renderTokens (array $tokens, array $options = [], $join = null) static
Exceptions
Referenced by TBela\CSS\Query\TokenSelectorValueAttributeFunctionColor\__construct(), TBela\CSS\Value\CssUrl\doRender(), TBela\CSS\Value\CssFunction\doRender(), TBela\CSS\Value\Color\doRender(), TBela\CSS\Ast\Traverser\doTraverse(), TBela\CSS\Query\TokenSelectorValueAttributeSelector\evaluate(), TBela\CSS\Parser\getAst(), TBela\CSS\Query\TokenSelectorValueAttributeFunctionColor\render(), TBela\CSS\Element\setValue(), and TBela\CSS\Parser\Validator\NestingAtRule\validate().
toObject()
TBela\CSS\Value::toObject ()
convert to an object
Returns
stdClass
Implements TBela\CSS\Interfaces\ObjectInterface.
type()
static TBela\CSS\Value::type () static protected
value type
Returns
string @ignore
Referenced by TBela\CSS\Value\ShortHand\matchPattern(), TBela\CSS\Value\BackgroundPosition\matchToken(), and TBela\CSS\Value\BackgroundSize\reduce().
validate()
static TBela\CSS\Value::validate ($data) static protected
test if $data matches this class
Parameters
stdClass $data
Returns
bool
Reimplemented in TBela\CSS\Value\Number, TBela\CSS\Value\Operator, TBela\CSS\Value\BackgroundImage, TBela\CSS\Value\Color, TBela\CSS\Value\InvalidCssString, TBela\CSS\Value\InvalidCssFunction, TBela\CSS\Value\Separator, TBela\CSS\Value\Comment, TBela\CSS\Value\CssFunction, TBela\CSS\Value\Whitespace, TBela\CSS\Value\Unit, TBela\CSS\Value\CssAttribute, TBela\CSS\Value\CssParenthesisExpression, TBela\CSS\Value\CssUrl, and TBela\CSS\Value\CssSrcFormat.
Member Data Documentation
$data
stdClass TBela\CSS\Value::$data = null protected
var stdClass; @ignore
Referenced by TBela\CSS\Value\Number\__construct(), TBela\CSS\Value\CssString\__construct(), TBela\CSS\Value\__construct(), TBela\CSS\Value\BackgroundPosition\__construct(), TBela\CSS\Value\InvalidCssFunction\doRecover(), TBela\CSS\Value\InvalidCssString\doRecover(), TBela\CSS\Value\CssUrl\doRender(), TBela\CSS\Value\CssFunction\doRender(), TBela\CSS\Value\BackgroundImage\doRender(), TBela\CSS\Value\Unit\doRender(), TBela\CSS\Value\Color\doRender(), TBela\CSS\Value\Unit\match(), TBela\CSS\Value\FontStyle\match(), TBela\CSS\Value\Number\match(), TBela\CSS\Value\CssSrcFormat\validate(), TBela\CSS\Value\CssParenthesisExpression\validate(), TBela\CSS\Value\CssUrl\validate(), TBela\CSS\Value\CssAttribute\validate(), TBela\CSS\Value\Unit\validate(), TBela\CSS\Value\CssFunction\validate(), TBela\CSS\Value\InvalidCssFunction\validate(), TBela\CSS\Value\Separator\validate(), TBela\CSS\Value\InvalidCssString\validate(), TBela\CSS\Value\Color\validate(), TBela\CSS\Value\BackgroundImage\validate(), TBela\CSS\Value\Operator\validate(), and TBela\CSS\Value\Number\validate().
The documentation for this class was generated from the following file:
src/Value.php