CSS: TBela\CSS\Query\Parser Class Reference
TBela\CSS\Query\Parser Class Reference
Public Member Functions
parse ($string)
split ($string, $char='|')
Protected Member Functions
doParse ($string)
parse_selectors ()
parse_selector ($selector, $context='selector')
getTokenType ($token, $context)
parse_path ()
is_whitespace ($char)
match_token ($string, $close, $position, $start)
Protected Attributes
$position
$last
$string
$tokens
Member Function Documentation
doParse()
TBela\CSS\Query\Parser::doParse ($string) protected
Parameters
string $string
Returns
array
Exceptions
SyntaxError
Referenced by TBela\CSS\Query\Parser\parse().
getTokenType()
TBela\CSS\Query\Parser::getTokenType ($token, $context) protected
Parameters
string $token
string $context
Returns
object
Referenced by TBela\CSS\Query\Parser\parse_selector().
parse()
TBela\CSS\Query\Parser::parse ($string)
Parameters
string $string
Returns
TokenList
Exceptions
SyntaxError
parse_path()
TBela\CSS\Query\Parser::parse_path () protected
Exceptions
SyntaxError
Referenced by TBela\CSS\Query\Parser\doParse().
parse_selector()
TBela\CSS\Query\Parser::parse_selector ($selector, $context = 'selector') protected
Parameters
string $selector
string $context
Returns
array
Exceptions
SyntaxError
Referenced by TBela\CSS\Query\Parser\parse_selectors().
parse_selectors()
TBela\CSS\Query\Parser::parse_selectors () protected
Exceptions
SyntaxError
Referenced by TBela\CSS\Query\Parser\doParse().
The documentation for this class was generated from the following file:
src/TBela/CSS/Query/Parser.php