CSS: TBela\CSS\Parser\Helper Class Reference
TBela\CSS\Parser\Helper Class Reference
Static Public Member Functions
static getCurrentDirectory ()
static resolvePath (string $file, string $path='')
static absolutePath ($file, $ref)
static relativePath (string $file, string $ref)
static isAbsolute ($path)
static fetchContent (string $url, array $options=[], array $curlOptions=[])
Static Protected Member Functions
static doParseUrl ($url)
static toUrl (array $data)
Static Protected Attributes
static bool $fixParseUrl
Member Function Documentation
absolutePath()
static TBela\CSS\Parser\Helper::absolutePath ($file, $ref) static
Parameters
string $file
string $ref
Returns
string
Referenced by TBela\CSS\Parser\append(), TBela\CSS\Parser\getAst(), TBela\CSS\Parser\Lexer\load(), TBela\CSS\Renderer\save(), TBela\CSS\Parser\setOptions(), and TBela\CSS\Parser\stream().
doParseUrl()
static TBela\CSS\Parser\Helper::doParseUrl ($url) static protected
fix parsing bug in parse_url for php < 8 : parse_url('/?#iefix') will not return the query string
Parameters
string $url
Returns
array @ignore
fetchContent()
static TBela\CSS\Parser\Helper::fetchContent (string $url, array $options = [], array $curlOptions = []) static
Parameters
string $url
array $options
array $curlOptions
Returns
bool|string @ignore
Referenced by TBela\CSS\Parser\append(), and TBela\CSS\Parser\Lexer\load().
getCurrentDirectory()
static TBela\CSS\Parser\Helper::getCurrentDirectory () static
Returns
string @ignore @ignore
Referenced by TBela\CSS\Parser\append(), TBela\CSS\Parser\Lexer\load(), TBela\CSS\Renderer\save(), TBela\CSS\Parser\setOptions(), and TBela\CSS\Parser\stream().
isAbsolute()
static TBela\CSS\Parser\Helper::isAbsolute ($path) static
Parameters
string $path
Returns
bool
relativePath()
static TBela\CSS\Parser\Helper::relativePath (string $file, string $ref) static
compute relative path
Parameters
string $file
string $ref relative directory
Returns
string
Referenced by TBela\CSS\Renderer\save().
resolvePath()
static TBela\CSS\Parser\Helper::resolvePath (string $file, string $path = '') static
Parameters
string $file
string $path
Returns
string @ignore
toUrl()
static TBela\CSS\Parser\Helper::toUrl (array $data) static protected
Parameters
array $data
Returns
string
The documentation for this class was generated from the following file:
src/Parser/Helper.php