CSS: TBela\CSS\Renderer Class Reference
TBela\CSS\Renderer Class Reference
Public Member Functions
__construct (array $options=[])
render (RenderableInterface $element, ?int $level=null, bool $parent=false)
renderAst (object $ast, ?int $level=null)
save (object $ast, $file)
setOptions (array $options)
getOptions ($name=null, $default=null)
flatten (object $node)
Protected Member Functions
walk (array $tree, object $position, ?int $level=0)
renderStylesheet (object $ast, ?int $level)
renderRule (object $ast, ?int $level)
renderAtRuleMedia (object $ast, ?int $level)
renderAtRule (object $ast, ?int $level)
renderCollection (object $ast, ?int $level)
renderNestingAtRule (object $ast, ?int $level)
renderNestingRule (object $ast, ?int $level)
renderNestingMediaRule (object $ast, ?int $level)
renderComment (object $ast, ?int $level)
renderSelector (object $ast, ?int $level)
renderDeclaration ($ast, ?int $level)
renderProperty (object $ast, ?int $level)
renderName (object $ast)
renderValue (object $ast)
addPosition ($generated, object $ast)
update (object $position, string $string)
flattenChildren (object $node)
Protected Attributes
array $options
string $outFile = ''
array $indents = []
SourceMap $sourcemap
Constructor & Destructor Documentation
__construct()
TBela\CSS\Renderer::__construct (array $options = [])
Identity constructor.
Parameters
array $options
Member Function Documentation
addPosition()
TBela\CSS\Renderer::addPosition ($generated, object $ast) protected
add sourcemap entry
Parameters
string $generated
object $ast
Returns
Renderer @ignore
Referenced by TBela\CSS\Renderer\walk().
flatten()
TBela\CSS\Renderer::flatten (object $node)
Parameters
object $node
Returns
object
Exceptions
Exception @ignore
Referenced by TBela\CSS\Renderer\renderAst(), and TBela\CSS\Renderer\save().
flattenChildren()
TBela\CSS\Renderer::flattenChildren (object $node) protected
flatten nested css tree
Parameters
object $node
Returns
object @ignore
getOptions()
TBela\CSS\Renderer::getOptions ($name = null, $default = null)
return the options
Parameters
string | null $name
mixed $default return value
Returns
array
render()
TBela\CSS\Renderer::render (RenderableInterface $element, ?int $level = null, bool $parent = false)
render an ElementInterface or a Property
Parameters
RenderableInterface $element the element to render
null | int $level indention level
bool $parent render parent
Returns
string
Exceptions
Exception
renderAst()
TBela\CSS\Renderer::renderAst (object $ast, ?int $level = null)
Parameters
object | ParsableInterface $ast
int | null $level
Returns
string
Exceptions
Exception
Referenced by TBela\CSS\Renderer\render().
renderAtRule()
TBela\CSS\Renderer::renderAtRule (object $ast, ?int $level) protected
render at-rule
Parameters
object $ast
int | null $level
Returns
string @ignore
Referenced by TBela\CSS\Renderer\renderNestingMediaRule().
renderAtRuleMedia()
TBela\CSS\Renderer::renderAtRuleMedia (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string @ignore
Referenced by TBela\CSS\Renderer\renderAtRule(), and TBela\CSS\Renderer\walk().
renderCollection()
TBela\CSS\Renderer::renderCollection (object $ast, ?int $level) protected
render a list
Parameters
object $ast
int | null $level
Returns
string @ignore
Referenced by TBela\CSS\Renderer\renderAst(), TBela\CSS\Renderer\renderAtRule(), TBela\CSS\Renderer\renderRule(), and TBela\CSS\Renderer\renderStylesheet().
renderComment()
TBela\CSS\Renderer::renderComment (object $ast, ?int $level) protected
Parameters
object $ast
int | null $level
Returns
string @ignore
renderDeclaration()
TBela\CSS\Renderer::renderDeclaration ($ast, ?int $level) protected
Parameters
\stdClass $ast
int | null $level
Returns
string @ignore
renderName()
TBela\CSS\Renderer::renderName (object $ast) protected
render a name
Parameters
object $ast
Returns
string @ignore
Referenced by TBela\CSS\Renderer\renderAtRuleMedia().
renderNestingAtRule()
TBela\CSS\Renderer::renderNestingAtRule (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string
Exceptions
Exception @ignore
renderNestingMediaRule()
TBela\CSS\Renderer::renderNestingMediaRule (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string @ignore
renderNestingRule()
TBela\CSS\Renderer::renderNestingRule (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string
Exceptions
Exception @ignore
renderProperty()
TBela\CSS\Renderer::renderProperty (object $ast, ?int $level) protected
render a property
Parameters
object $ast
int | null $level
Returns
string
Exceptions
Exception @ignore
renderRule()
TBela\CSS\Renderer::renderRule (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string
Exceptions
Exception @ignore
Referenced by TBela\CSS\Renderer\renderNestingAtRule(), and TBela\CSS\Renderer\renderNestingRule().
renderSelector()
TBela\CSS\Renderer::renderSelector (object $ast, ?int $level) protected
render a rule
Parameters
object $ast
int | null $level
Returns
string
Exceptions
Exception @ignore
Referenced by TBela\CSS\Renderer\renderRule(), and TBela\CSS\Renderer\walk().
renderStylesheet()
TBela\CSS\Renderer::renderStylesheet (object $ast, ?int $level) protected
Parameters
object $ast
int | null $level
Returns
string @ignore
renderValue()
TBela\CSS\Renderer::renderValue (object $ast) protected
render a value
Parameters
object $ast
Returns
string
Exceptions
Exception @ignore
Referenced by TBela\CSS\Renderer\renderAtRuleMedia().
save()
TBela\CSS\Renderer::save (object $ast, $file)
Parameters
object $ast
string $file
Returns
Renderer
Exceptions
IOException
setOptions()
TBela\CSS\Renderer::setOptions (array $options)
Set output formatting
Parameters
array $options
Returns
Renderer
Referenced by TBela\CSS\Renderer\__construct().
update()
TBela\CSS\Renderer::update (object $position, string $string) protected
Parameters
object $position
string $string
Returns
\stdClass @ignore
Referenced by TBela\CSS\Renderer\walk().
walk()
TBela\CSS\Renderer::walk (array $tree, object $position, ?int $level = 0) protected
Parameters
array $tree
object $position
int | null $level
Returns
void
Exceptions
Exception @ignore
Referenced by TBela\CSS\Renderer\save().
Member Data Documentation
$options
array TBela\CSS\Renderer::$options protected
Initial value:
= [
        'glue' => "\n",
        'indent' => ' ',
        'css_level' => 4,
        'separator' => ' ',
        'charset' => false,
        'compress' => false,
        'sourcemap' => false,
        'convert_color' => false,
        'remove_comments' => false,
        'preserve_license' => false,
        'legacy_rendering' => false,
        'compute_shorthand' => true,
        'remove_empty_nodes' => false,
        'allow_duplicate_declarations' => false
    ]
The documentation for this class was generated from the following file:
src/Renderer.php