#!/bin/php
<?php

use TBela\CSS\Cli\Exceptions\MissingParameterException;
use TBela\CSS\Parser;

require __DIR__ . '/../vendor/autoload.php';

// only use from the cli
if (php_sapi_name() != 'cli') {

    fwrite(STDERR, 'this program must be run from the cli');
    exit(1);
}

spl_autoload_register(function ($name) {

    $parts = explode('\\', $name);

    if ($parts[0] == 'TBela' && isset($parts[1]) && $parts[1] == 'CSS') {

        array_splice($parts, 0, 2);
        array_unshift($parts, 'src');
    }

    $path = __DIR__ . '/../' . implode('/', $parts) . '.php';

    if (is_file($path)) {

        require($path);
    }
});

$exe = basename($argv[0]);
$cli = new TBela\CSS\Cli\Args($argv);

try {

    $cli->
    setStrict(true);

    $cli->addGroup('parse', "parse options:\n");
    $cli->add('capture-errors', 'ignore parse error', 'bool', 'e', multiple: false, group: 'parse');
    $cli->add('flatten-import', 'process @import', 'bool', 'm', multiple: false, group: 'parse');
    $cli->add('parse-allow-duplicate-rules', 'allow duplicate rule', 'bool', 'p', multiple: false, group: 'parse');
    $cli->add('parse-allow-duplicate-declarations', 'allow duplicate declaration', type: 'auto', alias: 'd', multiple: false, group: 'parse');
    $cli->add('file', 'css file or url', 'string', 'f', multiple: true, group: 'parse');

    $cli->addGroup('render', "render options:\n");
    $cli->add('css-level', 'css color module', 'int', 'l', multiple: false, defaultValue: 4, group: 'render', options: [3, 4]);
    $cli->add('charset', 'remove @charset', 'bool', 'S', multiple: false, group: 'render', defaultValue: true);
    $cli->add('compress', 'minify output', 'bool', 'c', multiple: false, group: 'render');
    $cli->add('sourcemap', 'generate sourcemap, require -o', 'bool', 's', multiple: false, group: 'render');
    $cli->add('remove-comments', 'remove comments', 'bool', 'C', multiple: false, group: 'render');
    $cli->add('preserve-license', 'preserve license comments', 'bool', 'L', multiple: false, group: 'render');
    $cli->add('legacy-rendering', 'legacy rendering', 'bool', 'G', multiple: false, group: 'render');
    $cli->add('compute-shorthand', 'compute shorthand properties', 'bool', 'u', multiple: false, group: 'render');
    $cli->add('remove-empty-nodes', 'remove empty nodes', 'bool', 'E', multiple: false, group: 'render');
    $cli->add('render-duplicate-declarations', 'render duplicate declarations', 'bool', 'r', multiple: false, group: 'render');
    $cli->add('output', 'output file name', 'string', 'o', multiple: false, group: 'render');
    $cli->add('ast', 'dump ast as JSON', 'bool', 'a', multiple: false, group: 'render');

    $cli->parse();

    $parseOptions = [];
    $renderOptions = [];

    $groups = $cli->getGroups();
    $args = $cli->getArguments();

    $pipeIn = !posix_isatty(STDIN);
    $pipeOut = !posix_isatty(STDOUT);

    $inFile = $pipeIn ? STDIN : ($args['file'] ?? null);
    $outFile = $pipeOut ? STDOUT : ($args['output'] ?? STDOUT);

    if (isset($args['sourcemap']) && $outFile == STDOUT) {

        throw new InvalidArgumentException(sprintf("%s: --sourcemap requires --file parameter\nTry '%s --help'", $exe, $exe));
    }

    if ($inFile == STDIN && !empty($args['file'])) {

        fwrite(STDERR, "> notice: ignoring parameter --file\n");
    }

    if ($outFile == STDOUT && !empty($args['output'])) {

        fwrite(STDERR, "> notice: ignoring parameter --output\n");
    }

    foreach (array_keys($groups['parse']['arguments']) as $key) {

        if (isset($args[$key])) {

            $parseOptions[str_replace(['parse-', '-'], ['', '_'], $key)] = $args[$key];
        }
    }

    foreach (array_keys($groups['render']['arguments']) as $key) {

        if (isset($args[$key])) {

            $renderOptions[str_replace(['parse-', '-'], ['', '_'], $key)] = $args[$key];
        }
    }

    $parser = new Parser('', $parseOptions);

    if ($inFile) {

        if (!empty($args['_'])) {

            fwrite(STDERR, "> notice: ignoring inline css\n");
        }

        if ($inFile == STDIN) {

            $parser->appendContent(file_get_contents('php://stdin'));
        } else {

            foreach ((array)$inFile as $file) {

                $parser->load($file);
            }
        }
    } else if (!empty($args['_'])) {

            $parser->appendContent(implode('', $args['_']));
    } else {

        // no input
        exit(0);
    }

    if ($outFile) {

        if (!empty($args['ast'])) {

            if ($outFile == STDIN) {

                fwrite($outFile, json_encode($parser->getAst()));
            } else {

                if ($outFile == STDOUT) {

                    fwrite($outFile, json_encode($parser->getAst(), empty($renderOptions['compress']) ? JSON_PRETTY_PRINT : 0));
                } else {

                    file_put_contents($outFile, json_encode($parser->getAst(), empty($renderOptions['compress']) ? JSON_PRETTY_PRINT : 0));
                }
            }

        } else {

            $renderer = new \TBela\CSS\Renderer($renderOptions);

            if ($outFile == STDOUT) {

                fwrite($outFile, $renderer->renderAst($parser));
            } else {

                $renderer->save($parser, $outFile);
            }
        }
    }
} catch (ValueError|UnexpectedValueException|InvalidArgumentException $e) {

    fwrite(STDERR, $e->getMessage() . "\n");
    exit($e->getCode());
} catch (MissingParameterException $e) {

    fwrite(STDERR, sprintf("%s: %s\nTry '%s --help'\n", $exe, $e->getMessage(), $exe));
    exit($e->getCode());
} catch (Exception $e) {

    fwrite(STDERR, $e->getMessage() . "\n");
    exit(1);
}