CSS: TBela\CSS\Parser Class Reference
TBela\CSS\Parser Class Reference
Public Member Functions
__construct (string $css='', array $options=[])
slice ($css, $position, $size)
on (string $event, callable $callable)
off (string $event, callable $callable)
append (string $file, string $media='')
appendContent (string $css, string $media='')
merge (Parser $parser)
setContent (string $css, string $media='')
load (string $file, string $media='')
setOptions (array $options)
parse ()
getAst ()
deduplicate (object $ast, ?int $index=null)
getErrors ()
__toString ()
Protected Member Functions
enQueue ($src, $buffer, $position)
stream (string $content, object $root, string $file)
emit (Exception $error)
reset ()
computeSignature (object $ast)
deduplicateRules (object $ast, ?int $index=null)
deduplicateDeclarations (object $ast)
handleError (string $message, int $error_code=400)
validate (object $token, object $parentRule, object $parentStylesheet)
getContext ()
pushContext (object $context)
popContext ()
enterNode (object $token, object $parentRule, object $parentStylesheet)
exitNode (object $token)
doValidate (object $token, object $context, object $parentStylesheet)
Protected Attributes
array $context = []
Lexer $lexer
array $errors = []
string $error
object $ast = null
array $options
Pool $pool
array $output = []
int $lastDedupIndex = null
string $format = 'serialize'
Static Protected Attributes
static array $validators = []
Constructor & Destructor Documentation
__construct()
TBela\CSS\Parser::__construct (string $css = '', array $options = [])
Parser constructor.
Parameters
string $css
array $options
Exceptions
IOException
SyntaxError
Member Function Documentation
append()
TBela\CSS\Parser::append (string $file, string $media = '')
parse css file and append to the existing AST
Parameters
string $file
string $media
Returns
Parser
Exceptions
Exception
Referenced by TBela\CSS\Parser\getAst().
appendContent()
TBela\CSS\Parser::appendContent (string $css, string $media = '')
parse css and append to the existing AST
Parameters
string $css
string $media
Returns
Parser
Exceptions
SyntaxError|Exception
computeSignature()
TBela\CSS\Parser::computeSignature (object $ast) protected
compute signature
Parameters
object $ast
Returns
string @ignore
Referenced by TBela\CSS\Parser\deduplicateDeclarations(), and TBela\CSS\Parser\deduplicateRules().
deduplicate()
TBela\CSS\Parser::deduplicate (object $ast, ?int $index = null)
Parameters
object $ast
int | null $index
Returns
object
Referenced by TBela\CSS\Parser\deduplicateRules(), and TBela\CSS\Parser\getAst().
deduplicateDeclarations()
TBela\CSS\Parser::deduplicateDeclarations (object $ast) protected
Parameters
object $ast
Returns
object
Referenced by TBela\CSS\Parser\deduplicate().
deduplicateRules()
TBela\CSS\Parser::deduplicateRules (object $ast, ?int $index = null) protected
Parameters
object $ast
int | null $index
Returns
object
Referenced by TBela\CSS\Parser\deduplicate().
doValidate()
TBela\CSS\Parser::doValidate (object $token, object $context, object $parentStylesheet) protected
perform the syntax validation
Parameters
object $token
object $context
object $parentStylesheet
Returns
int
Exceptions
SyntaxError @ignore
Referenced by TBela\CSS\Parser\enterNode().
emit()
TBela\CSS\Parser::emit (Exception $error) protected
Parameters
Exception $error
Returns
void
Referenced by TBela\CSS\Parser\handleError(), and TBela\CSS\Parser\Lexer\load().
enterNode()
TBela\CSS\Parser::enterNode (object $token, object $parentRule, object $parentStylesheet) protected
parse event handler
Parameters
object $token
object $parentRule
object $parentStylesheet
Returns
int
Exceptions
SyntaxError @ignore
exitNode()
TBela\CSS\Parser::exitNode (object $token) protected
parse event handler
Parameters
object $token
Returns
void
Exceptions
SyntaxError @ignore
getAst()
TBela\CSS\Parser::getAst ()
@inheritDoc
Exceptions
SyntaxError|Exception
Implements TBela\CSS\Interfaces\ParsableInterface.
Referenced by TBela\CSS\Parser\getContext(), TBela\CSS\Parser\merge(), and TBela\CSS\Parser\parse().
getContext()
TBela\CSS\Parser::getContext () protected
get the current parent node
Returns
object|null
Exceptions
SyntaxError @ignore
Referenced by TBela\CSS\Parser\append(), TBela\CSS\Parser\appendContent(), TBela\CSS\Parser\enterNode(), and TBela\CSS\Parser\exitNode().
getErrors()
TBela\CSS\Parser::getErrors ()
return parse errors
Returns
Exception[]
handleError()
TBela\CSS\Parser::handleError (string $message, int $error_code = 400) protected
Parameters
string $message
int $error_code
Returns
SyntaxError
Exceptions
SyntaxError
Referenced by TBela\CSS\Parser\doValidate(), and TBela\CSS\Parser\enterNode().
load()
TBela\CSS\Parser::load (string $file, string $media = '')
load css content from a file
Parameters
string $file
string $media
Returns
Parser
Exceptions
Exceptions
merge()
TBela\CSS\Parser::merge (Parser $parser)
Parameters
Parser $parser
Returns
Parser
Exceptions
SyntaxError
off()
TBela\CSS\Parser::off (string $event, callable $callable)
Parameters
string $event parse event name in ['enter', 'exit', 'start', 'end']
callable $callable
Returns
Parser
on()
TBela\CSS\Parser::on (string $event, callable $callable)
Parameters
string $event parse event name in ['enter', 'exit']
callable $callable
Returns
Parser
Referenced by TBela\CSS\Parser\__construct(), and TBela\CSS\Parser\Lexer\load().
parse()
TBela\CSS\Parser::parse ()
parse Css
Returns
RuleListInterface|null
Exceptions
SyntaxError
popContext()
TBela\CSS\Parser::popContext () protected
pop the current parent node
Returns
void @ignore
Referenced by TBela\CSS\Parser\append(), TBela\CSS\Parser\exitNode(), and TBela\CSS\Parser\getAst().
pushContext()
TBela\CSS\Parser::pushContext (object $context) protected
push the current parent node
Parameters
object $context
Returns
void @ignore
Referenced by TBela\CSS\Parser\append(), TBela\CSS\Parser\enterNode(), and TBela\CSS\Parser\getAst().
setContent()
TBela\CSS\Parser::setContent (string $css, string $media = '')
set css content
Parameters
string $css
string $media
Returns
Parser
Exceptions
IOException
SyntaxError
Referenced by TBela\CSS\Parser\__construct(), and TBela\CSS\Parser\appendContent().
setOptions()
TBela\CSS\Parser::setOptions (array $options)
set the parser options
Parameters
array $options
Returns
Parser
Referenced by TBela\CSS\Parser\__construct().
stream()
TBela\CSS\Parser::stream (string $content, object $root, string $file) protected
Parameters
string $content
object $root
string $file
Returns
void
Referenced by TBela\CSS\Parser\append(), and TBela\CSS\Parser\appendContent().
validate()
TBela\CSS\Parser::validate (object $token, object $parentRule, object $parentStylesheet) protected
syntax validation
Parameters
object $token
object $parentRule
object $parentStylesheet
Returns
int @ignore
Referenced by TBela\CSS\Parser\doValidate().
Member Data Documentation
$options
array TBela\CSS\Parser::$options protected
Initial value:
= [
        'capture_errors' => true,
        'flatten_import' => false,
        'allow_duplicate_rules' => ['font-face'],
        'allow_duplicate_declarations' => true,
        'multi_processing' => true,
        'multi_processing_threshold' => 66560,
        'children_process' => 20,
        'ast_src' => '',
        'ast_position_line' => 1,
        'ast_position_column' => 1,
        'ast_position_index' => 0
    ]
The documentation for this class was generated from the following file:
src/Parser.php