CSS: TBela\CSS\Value\Set Class Reference
TBela\CSS\Value\Set Class Reference
Public Member Functions
__construct (array $data=[])
__get ($name)
getHash ()
render (array $options=[])
match (string $type)
filter (callable $filter)
map (callable $map)
merge (Set ... $sets)
split (string $separator)
add (Value $value)
__toString ()
toArray ()
toObject ()
getIterator ()
jsonSerialize ()
count ()
Protected Member Functions
doSplit (array $data, string $separator)
Protected Attributes
array $data = []
Constructor & Destructor Documentation
__construct()
TBela\CSS\Value\Set::__construct (array $data = [])
Set constructor.
Parameters
Value[] $data
Member Function Documentation
__get()
TBela\CSS\Value\Set::__get ($name)
Parameters
string $name
Returns
mixed|null @ignore
__toString()
TBela\CSS\Value\Set::__toString ()
Automatically convert this object to string
Returns
string
add()
TBela\CSS\Value\Set::add (Value $value)
add an item to the set
Parameters
Value $value
Returns
$this
Referenced by TBela\CSS\Property\PropertyMap\set().
count()
TBela\CSS\Value\Set::count ()
Returns
int
Referenced by TBela\CSS\Value\Set\merge().
doSplit()
TBela\CSS\Value\Set::doSplit (array $data, string $separator) protected
Parameters
array $data
string $separator
Returns
Set[] @ignore
Referenced by TBela\CSS\Value\Set\render(), and TBela\CSS\Value\Set\split().
filter()
TBela\CSS\Value\Set::filter (callable $filter)
filter values
Parameters
callable $filter
Returns
$this
getIterator()
TBela\CSS\Value\Set::getIterator ()
@inheritDoc
jsonSerialize()
TBela\CSS\Value\Set::jsonSerialize ()
@inheritDoc
map()
TBela\CSS\Value\Set::map (callable $map)
map values
Parameters
callable $map
Returns
$this
match()
TBela\CSS\Value\Set::match (string $type)
Parameters
string $type
Returns
bool
merge()
TBela\CSS\Value\Set::merge (Set ... $sets)
append the second set data to the first set data
Parameters
Set[] $sets
Returns
Set
render()
TBela\CSS\Value\Set::render (array $options = [])
Convert this object to string
Parameters
array $options
Returns
string
Referenced by TBela\CSS\Value\Set\__toString().
split()
TBela\CSS\Value\Set::split (string $separator)
split a set according to $separator
Parameters
string $separator
Returns
Set[]
toArray()
TBela\CSS\Value\Set::toArray ()
return an array of internal data
Returns
Value[]
Referenced by TBela\CSS\Property\PropertyMap\set().
toObject()
TBela\CSS\Value\Set::toObject ()
@inheritDoc
Implements TBela\CSS\Interfaces\ObjectInterface.
The documentation for this class was generated from the following file:
src/TBela/CSS/Value/Set.php