<?php 

namespace TBela\CSS;

use Exception;

/**
 * Css Compiler
 * @package TBela\CSS
 */
class Compiler {

    /**
     * @var array
     * @ignore
     */
    protected $options = [
	    'indent' => ' ',
        'glue' => "\n",
        'separator' => ' ',
        'charset' => false,
        'rgba_hex' => false,
        'compress' => false,
        'css_level' => 3,
        'remove_comments' => false,
        'remove_empty_nodes' => true,
        'allow_duplicate_declarations' => ['background-image']
    ];

    /**
     * @var Element
     * @ignore
     */
	protected $data;

    /**
     * Compiler constructor.
     * @param array $options
     */
	public function __construct (array $options = []) {

		$this->setOptions($options);
	}

    /**
     * set compiler options
     * @param array $options
     * @return $this
     */
	public function setOptions (array $options) {

	    foreach (array_keys($this->options) as $key) {

	        if (isset($options[$key])) {

	            $this->options[$key] = $options[$key];
            }
        }

	    return $this;
    }

    /**
     * set css content
     * @param string $css
     * @return Compiler
     * @throws Exception
     */
	public function setContent ($css) {

	    $this->data = Element::getInstance((new Parser($css, $this->options))->parse());
	    return $this;
    }

    /**
     * load css content from a file
     * @param string $file
     * @return $this
     * @throws Exception
     */
    public function load ($file) {

        $this->data = Element::getInstance((new Parser('', $this->options))->load($file)->parse());
        return $this;
    }

    /**
     * load content from an element or AST
     * @param Element|object $ast
     * @return Compiler
     */
	public function setData ($ast) {

		$this->data = Element::getInstance($ast);
		return $this;
	}

    /**
     * return the element generated by the css parser
     * @return Element
     */
    public function getData () {

        return $this->data;
    }

    /**
     * compile css
     * @return string
     * @throws Exception
     */
	public function compile () {

		if (isset($this->data)) {

			return (new Renderer($this->options))->render($this->data);
		}

		return '';
	}
}
