CSS: TBela\CSS\Element Class Reference
TBela\CSS\Element Class Reference
Public Member Functions
__construct ($ast=null, $parent=null)
traverse (callable $fn, $event)
query ($query)
queryByClassNames ($query)
getRoot ()
getValue ()
getRawValue ()
setValue ($value)
getParent ()
getType ()
copy ()
getSrc ()
getPosition ()
setTrailingComments (?array $comments)
getTrailingComments ()
setLeadingComments (?array $comments)
getLeadingComments ()
deduplicate (array $options=['allow_duplicate_rules'=>['font-face']])
setAst (ElementInterface $element)
getAst ()
jsonSerialize ()
__toString ()
__clone ()
toObject ()
Public Member Functions inherited from TBela\CSS\Query\QueryInterface
query (string $query)
Static Public Member Functions
static getInstance ($ast)
static from ($css, array $options=[])
static fromUrl ($url, array $options=[])
Protected Member Functions
setComments (?array $comments, $type)
computeSignature ()
deduplicateDeclarations (array $options=[])
Protected Attributes
object $ast = null
RuleListInterface $parent = null
array $rawValue = null
Constructor & Destructor Documentation
__construct()
TBela\CSS\Element::__construct ($ast = null, $parent = null)
Element constructor.
Parameters
object | null $ast
RuleListInterface | null $parent
Exceptions
Exception
Member Function Documentation
__clone()
TBela\CSS\Element::__clone ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
__toString()
TBela\CSS\Element::__toString ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
computeSignature()
TBela\CSS\Element::computeSignature () protected
compute signature
Returns
string @ignore
copy()
TBela\CSS\Element::copy ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
deduplicate()
TBela\CSS\Element::deduplicate (array $options = ['allow_duplicate_rules' =, ['font-face'] ])
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
deduplicateDeclarations()
TBela\CSS\Element::deduplicateDeclarations (array $options = []) protected
merge duplicate declarations
Returns
Element @ignore
from()
static TBela\CSS\Element::from ($css, array $options = []) static
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
fromUrl()
static TBela\CSS\Element::fromUrl ($url, array $options = []) static
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getAst()
TBela\CSS\Element::getAst ()
return the ast
Returns
\stdClass|null
Implements TBela\CSS\Interfaces\ParsableInterface.
getInstance()
static TBela\CSS\Element::getInstance ($ast) static
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
Referenced by TBela\CSS\Element\copy(), TBela\CSS\Parser\parse(), and TBela\CSS\Element\RuleList\setChildren().
getLeadingComments()
TBela\CSS\Element::getLeadingComments ()
@inheritDoc
Implements TBela\CSS\Interfaces\RenderableInterface.
getParent()
TBela\CSS\Element::getParent ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getPosition()
TBela\CSS\Element::getPosition ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getRawValue()
TBela\CSS\Element::getRawValue ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getRoot()
TBela\CSS\Element::getRoot ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getSrc()
TBela\CSS\Element::getSrc ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getTrailingComments()
TBela\CSS\Element::getTrailingComments ()
@inheritDoc
Implements TBela\CSS\Interfaces\RenderableInterface.
getType()
TBela\CSS\Element::getType ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
getValue()
TBela\CSS\Element::getValue ()
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
jsonSerialize()
TBela\CSS\Element::jsonSerialize ()
Returns
stdClass @ignore
Reimplemented in TBela\CSS\Element\AtRule.
query()
TBela\CSS\Element::query ($query)
@inheritDoc
Exceptions
Parser
Implements TBela\CSS\Interfaces\ElementInterface.
queryByClassNames()
TBela\CSS\Element::queryByClassNames ($query)
@inheritDoc
Exceptions
Parser
Implements TBela\CSS\Interfaces\ElementInterface.
setComments()
TBela\CSS\Element::setComments (?array $comments, $type) protected
Parameters
string[] | Value\Comment[] | null $comments
Returns
Element
setLeadingComments()
TBela\CSS\Element::setLeadingComments (?array $comments)
@inheritDoc
Implements TBela\CSS\Interfaces\RenderableInterface.
setTrailingComments()
TBela\CSS\Element::setTrailingComments (?array $comments)
@inheritDoc
Implements TBela\CSS\Interfaces\RenderableInterface.
setValue()
TBela\CSS\Element::setValue ($value)
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
toObject()
TBela\CSS\Element::toObject ()
@inheritDoc
Implements TBela\CSS\Interfaces\ObjectInterface.
traverse()
TBela\CSS\Element::traverse (callable $fn, $event)
@inheritDoc
Implements TBela\CSS\Interfaces\ElementInterface.
Member Data Documentation
$parent
RuleListInterface TBela\CSS\Element::$parent = null protected
@ignore
Referenced by TBela\CSS\Element\__construct(), and TBela\CSS\Element\RuleList\insert().
The documentation for this class was generated from the following file:
src/Element.php